name: "CD"

on:
  schedule:
    # twice per month
    - cron: "10 5 1,14 * *"
  push:
    tags:
      - "v*.*.*"

jobs:
  Testing:
    uses: milejko/kuick-project/.github/workflows/ci.yml@main

  Deployment:
    needs: Testing
    strategy:
      matrix:
        # Ubuntu Noble is not available for now, because of a curl arm64 bug:
        # https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2073448
        os-variant: ['jammy', 'bookworm', 'alpine']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Set up QEMU (multiplatform)
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx (multiplatform)
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: kuickphp/kuick
        tags: |
          type=raw,value=${{ matrix.os-variant }}
          type=semver,pattern={{major}},suffix=-${{ matrix.os-variant }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.os-variant }}
          type=semver,pattern={{major}},enable=${{ 'jammy' == matrix.os-variant }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ 'jammy' == matrix.os-variant }}
          type=raw,value=latest,enable=${{ 'jammy' == matrix.os-variant }}
    - 
      name: Build & push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        target: dist
        tags: ${{ steps.meta.outputs.tags }},
        labels: ${{ steps.meta.outputs.labels }},
        build-args: |
          PHP_VERSION=8.3
          OS_VARIANT=${{ matrix.os-variant }}
